"""Initial migration with all models

Revision ID: 7985aab4feeb
Revises: 
Create Date: 2026-02-16 23:32:04.732434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7985aab4feeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=100), nullable=False),
    sa.Column('game_uid', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('home_team', sa.String(length=20), nullable=True),
    sa.Column('away_team', sa.String(length=20), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('league', sa.String(length=30), nullable=True),
    sa.Column('total_pitches', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_uid')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_away_team'), ['away_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_game_id'), ['game_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_games_home_team'), ['home_team'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trackman_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('throws', sa.String(length=10), nullable=True),
    sa.Column('bats', sa.String(length=10), nullable=True),
    sa.Column('primary_position', sa.String(length=20), nullable=True),
    sa.Column('team', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team'), ['team'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_trackman_id'), ['trackman_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('team_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_code', sa.String(length=20), nullable=False),
    sa.Column('team_name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('league', sa.String(length=50), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('accent_color', sa.String(length=7), nullable=True),
    sa.Column('logo_filename', sa.String(length=100), nullable=True),
    sa.Column('is_main_team', sa.Boolean(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_code')
    )
    with op.batch_alter_table('team_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_config_is_main_team'), ['is_main_team'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('upload_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('game_id', sa.String(length=100), nullable=True),
    sa.Column('rows_total', sa.Integer(), nullable=True),
    sa.Column('rows_imported', sa.Integer(), nullable=True),
    sa.Column('rows_skipped', sa.Integer(), nullable=True),
    sa.Column('rows_error', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('upload_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_upload_logs_file_hash'), ['file_hash'], unique=False)

    op.create_table('pitches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_log_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pitch_no', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.String(length=20), nullable=True),
    sa.Column('pa_of_inning', sa.Integer(), nullable=True),
    sa.Column('pitch_of_pa', sa.Integer(), nullable=True),
    sa.Column('pitcher', sa.String(length=100), nullable=True),
    sa.Column('pitcher_id', sa.Integer(), nullable=True),
    sa.Column('pitcher_throws', sa.String(length=5), nullable=True),
    sa.Column('pitcher_team', sa.String(length=50), nullable=True),
    sa.Column('batter', sa.String(length=100), nullable=True),
    sa.Column('batter_id', sa.Integer(), nullable=True),
    sa.Column('batter_side', sa.String(length=5), nullable=True),
    sa.Column('batter_team', sa.String(length=50), nullable=True),
    sa.Column('pitcher_set', sa.String(length=20), nullable=True),
    sa.Column('inning', sa.Integer(), nullable=True),
    sa.Column('top_bottom', sa.String(length=10), nullable=True),
    sa.Column('outs', sa.Integer(), nullable=True),
    sa.Column('balls', sa.Integer(), nullable=True),
    sa.Column('strikes', sa.Integer(), nullable=True),
    sa.Column('tagged_pitch_type', sa.String(length=30), nullable=True),
    sa.Column('auto_pitch_type', sa.String(length=30), nullable=True),
    sa.Column('pitch_call', sa.String(length=30), nullable=True),
    sa.Column('k_or_bb', sa.String(length=20), nullable=True),
    sa.Column('tagged_hit_type', sa.String(length=30), nullable=True),
    sa.Column('play_result', sa.String(length=30), nullable=True),
    sa.Column('outs_on_play', sa.Integer(), nullable=True),
    sa.Column('runs_scored', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rel_speed', sa.Float(), nullable=True),
    sa.Column('vert_rel_angle', sa.Float(), nullable=True),
    sa.Column('horz_rel_angle', sa.Float(), nullable=True),
    sa.Column('spin_rate', sa.Float(), nullable=True),
    sa.Column('spin_axis', sa.Float(), nullable=True),
    sa.Column('tilt', sa.String(length=10), nullable=True),
    sa.Column('rel_height', sa.Float(), nullable=True),
    sa.Column('rel_side', sa.Float(), nullable=True),
    sa.Column('extension', sa.Float(), nullable=True),
    sa.Column('vert_break', sa.Float(), nullable=True),
    sa.Column('induced_vert_break', sa.Float(), nullable=True),
    sa.Column('horz_break', sa.Float(), nullable=True),
    sa.Column('plate_loc_height', sa.Float(), nullable=True),
    sa.Column('plate_loc_side', sa.Float(), nullable=True),
    sa.Column('zone_speed', sa.Float(), nullable=True),
    sa.Column('vert_appr_angle', sa.Float(), nullable=True),
    sa.Column('horz_appr_angle', sa.Float(), nullable=True),
    sa.Column('zone_time', sa.Float(), nullable=True),
    sa.Column('exit_speed', sa.Float(), nullable=True),
    sa.Column('angle', sa.Float(), nullable=True),
    sa.Column('direction', sa.Float(), nullable=True),
    sa.Column('hit_spin_rate', sa.Float(), nullable=True),
    sa.Column('position_at_110_x', sa.Float(), nullable=True),
    sa.Column('position_at_110_y', sa.Float(), nullable=True),
    sa.Column('position_at_110_z', sa.Float(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('last_tracked_distance', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('hang_time', sa.Float(), nullable=True),
    sa.Column('pfx_x', sa.Float(), nullable=True),
    sa.Column('pfx_z', sa.Float(), nullable=True),
    sa.Column('x0', sa.Float(), nullable=True),
    sa.Column('y0', sa.Float(), nullable=True),
    sa.Column('z0', sa.Float(), nullable=True),
    sa.Column('vx0', sa.Float(), nullable=True),
    sa.Column('vy0', sa.Float(), nullable=True),
    sa.Column('vz0', sa.Float(), nullable=True),
    sa.Column('ax0', sa.Float(), nullable=True),
    sa.Column('ay0', sa.Float(), nullable=True),
    sa.Column('az0', sa.Float(), nullable=True),
    sa.Column('home_team', sa.String(length=50), nullable=True),
    sa.Column('away_team', sa.String(length=50), nullable=True),
    sa.Column('stadium', sa.String(length=100), nullable=True),
    sa.Column('level', sa.String(length=30), nullable=True),
    sa.Column('league', sa.String(length=30), nullable=True),
    sa.Column('game_id', sa.String(length=100), nullable=True),
    sa.Column('pitch_uid', sa.String(length=64), nullable=False),
    sa.Column('effective_velo', sa.Float(), nullable=True),
    sa.Column('max_height', sa.Float(), nullable=True),
    sa.Column('measured_duration', sa.Float(), nullable=True),
    sa.Column('speed_drop', sa.Float(), nullable=True),
    sa.Column('pitch_last_measured_x', sa.Float(), nullable=True),
    sa.Column('pitch_last_measured_y', sa.Float(), nullable=True),
    sa.Column('pitch_last_measured_z', sa.Float(), nullable=True),
    sa.Column('contact_position_x', sa.Float(), nullable=True),
    sa.Column('contact_position_y', sa.Float(), nullable=True),
    sa.Column('contact_position_z', sa.Float(), nullable=True),
    sa.Column('game_uid', sa.String(length=64), nullable=True),
    sa.Column('utc_date', sa.Date(), nullable=True),
    sa.Column('utc_time', sa.String(length=20), nullable=True),
    sa.Column('local_date_time', sa.String(length=40), nullable=True),
    sa.Column('utc_date_time', sa.String(length=40), nullable=True),
    sa.Column('auto_hit_type', sa.String(length=30), nullable=True),
    sa.Column('system', sa.String(length=30), nullable=True),
    sa.Column('home_team_foreign_id', sa.Integer(), nullable=True),
    sa.Column('away_team_foreign_id', sa.Integer(), nullable=True),
    sa.Column('game_foreign_id', sa.String(length=64), nullable=True),
    sa.Column('catcher', sa.String(length=100), nullable=True),
    sa.Column('catcher_id', sa.Integer(), nullable=True),
    sa.Column('catcher_throws', sa.String(length=5), nullable=True),
    sa.Column('catcher_team', sa.String(length=50), nullable=True),
    sa.Column('play_id', sa.String(length=64), nullable=True),
    sa.Column('pitch_trajectory_xc0', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_xc1', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_xc2', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_yc0', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_yc1', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_yc2', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_zc0', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_zc1', sa.Float(), nullable=True),
    sa.Column('pitch_trajectory_zc2', sa.Float(), nullable=True),
    sa.Column('hit_spin_axis', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc0', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc1', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc2', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc3', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc4', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc5', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc6', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc7', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_xc8', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc0', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc1', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc2', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc3', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc4', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc5', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc6', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc7', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_yc8', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc0', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc1', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc2', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc3', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc4', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc5', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc6', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc7', sa.Float(), nullable=True),
    sa.Column('hit_trajectory_zc8', sa.Float(), nullable=True),
    sa.Column('throw_speed', sa.Float(), nullable=True),
    sa.Column('pop_time', sa.Float(), nullable=True),
    sa.Column('exchange_time', sa.Float(), nullable=True),
    sa.Column('time_to_base', sa.Float(), nullable=True),
    sa.Column('catch_position_x', sa.Float(), nullable=True),
    sa.Column('catch_position_y', sa.Float(), nullable=True),
    sa.Column('catch_position_z', sa.Float(), nullable=True),
    sa.Column('throw_position_x', sa.Float(), nullable=True),
    sa.Column('throw_position_y', sa.Float(), nullable=True),
    sa.Column('throw_position_z', sa.Float(), nullable=True),
    sa.Column('base_position_x', sa.Float(), nullable=True),
    sa.Column('base_position_y', sa.Float(), nullable=True),
    sa.Column('base_position_z', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_xc0', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_xc1', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_xc2', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_yc0', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_yc1', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_yc2', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_zc0', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_zc1', sa.Float(), nullable=True),
    sa.Column('throw_trajectory_zc2', sa.Float(), nullable=True),
    sa.Column('pitch_release_confidence', sa.Float(), nullable=True),
    sa.Column('pitch_location_confidence', sa.Float(), nullable=True),
    sa.Column('pitch_movement_confidence', sa.Float(), nullable=True),
    sa.Column('hit_launch_confidence', sa.Float(), nullable=True),
    sa.Column('hit_landing_confidence', sa.Float(), nullable=True),
    sa.Column('catcher_throw_catch_confidence', sa.Float(), nullable=True),
    sa.Column('catcher_throw_release_confidence', sa.Float(), nullable=True),
    sa.Column('catcher_throw_location_confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.game_id'], ),
    sa.ForeignKeyConstraint(['upload_log_id'], ['upload_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.create_index('ix_pitches_batter_date', ['batter_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_batter_id'), ['batter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_game_id'), ['game_id'], unique=False)
        batch_op.create_index('ix_pitches_game_inning', ['game_id', 'inning', 'top_bottom'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_pitch_uid'), ['pitch_uid'], unique=True)
        batch_op.create_index('ix_pitches_pitcher_date', ['pitcher_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_pitcher_id'), ['pitcher_id'], unique=False)
        batch_op.create_index('ix_pitches_pitcher_pitch_type', ['pitcher_id', 'tagged_pitch_type'], unique=False)
        batch_op.create_index('ix_pitches_pitcher_team_date', ['pitcher_team', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_pitches_upload_log_id'), ['upload_log_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pitches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pitches_upload_log_id'))
        batch_op.drop_index('ix_pitches_pitcher_team_date')
        batch_op.drop_index('ix_pitches_pitcher_pitch_type')
        batch_op.drop_index(batch_op.f('ix_pitches_pitcher_id'))
        batch_op.drop_index('ix_pitches_pitcher_date')
        batch_op.drop_index(batch_op.f('ix_pitches_pitch_uid'))
        batch_op.drop_index('ix_pitches_game_inning')
        batch_op.drop_index(batch_op.f('ix_pitches_game_id'))
        batch_op.drop_index(batch_op.f('ix_pitches_date'))
        batch_op.drop_index(batch_op.f('ix_pitches_batter_id'))
        batch_op.drop_index('ix_pitches_batter_date')

    op.drop_table('pitches')
    with op.batch_alter_table('upload_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_upload_logs_file_hash'))

    op.drop_table('upload_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('team_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_config_is_main_team'))

    op.drop_table('team_config')
    op.drop_table('roles')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_trackman_id'))
        batch_op.drop_index(batch_op.f('ix_players_team'))
        batch_op.drop_index(batch_op.f('ix_players_name'))

    op.drop_table('players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_home_team'))
        batch_op.drop_index(batch_op.f('ix_games_game_id'))
        batch_op.drop_index(batch_op.f('ix_games_date'))
        batch_op.drop_index(batch_op.f('ix_games_away_team'))

    op.drop_table('games')
    # ### end Alembic commands ###
